spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
#    root: debug
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  error:
    include-stacktrace: never  # 클라이언트 로그에 trace 를 노출하지 않기 위함
#server:
#  servlet:
#    session:
#      tracking-modes: cookie
##      timeout: 30

jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Q=
  token-validity-in-seconds: 86400

