spring:

  h2:
    console:
      enabled: true

  datasource:
#    url: jdbc:h2:tcp://localhost/~/test1
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#  main:
#    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Qtc3ByaW5nLWJvb3Qtc2VjcnVpdHktand0LXRva2VuLXRlc3Q=
  token-validity-in-seconds: 86400